;核心数据库配置
[main]

;写库
write.host    = SAE_MYSQL_HOST_M
write.port    = SAE_MYSQL_PORT
write.user    = SAE_MYSQL_USER
write.pass    = SAE_MYSQL_PASS
write.name    = SAE_MYSQL_DB
write.charset = "utf8"

;读库
read.host    = SAE_MYSQL_HOST_S
read.port    = SAE_MYSQL_PORT
read.user    = SAE_MYSQL_USER
read.pass    = SAE_MYSQL_PASS
read.name    = SAE_MYSQL_DB
read.charset = "utf8"